# Generated by Django 5.2.7 on 2025-11-25 23:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_publicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'indicador',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nivel_educativo', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(default='activa', max_length=50)),
            ],
            options={
                'db_table': 'institucion',
            },
        ),
        migrations.CreateModel(
            name='ModeloIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('metrica_precision', models.FloatField()),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('ruta_fichero', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modelo_ia',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='respuestaencuesta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='respuestaitem',
            name='respuesta_encuesta',
        ),
        migrations.RemoveField(
            model_name='respuestaitem',
            name='pregunta',
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['encuesta', 'orden']},
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta1',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta2',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta3',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta4',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta5',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='resultado',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(default='activa', max_length=50),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='titulo',
            field=models.CharField(default='Encuesta sin titulo', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='encuesta',
            table='encuesta',
        ),
        migrations.AlterModelTable(
            name='pregunta',
            table='pregunta',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestas.institucion'),
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
                ('valor_numerico', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='encuestas.pregunta')),
            ],
            options={
                'db_table': 'opcion_respuesta',
            },
        ),
        migrations.CreateModel(
            name='RecursoColaborativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurso_colaborativo',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_abierto', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta')),
                ('opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuestas.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='ResultadoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_madurez', models.CharField(max_length=50)),
                ('puntuacion_global', models.FloatField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.institucion')),
            ],
            options={
                'db_table': 'resultado_encuesta',
            },
        ),
        migrations.CreateModel(
            name='PrediccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_pred', models.CharField(max_length=50)),
                ('probabilidad', models.FloatField()),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.modeloia')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.resultadoencuesta')),
            ],
            options={
                'db_table': 'prediccion_ia',
            },
        ),
        migrations.CreateModel(
            name='ResultadoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('nivel_indicador', models.CharField(max_length=50)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.indicador')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_indicadores', to='encuestas.resultadoencuesta')),
            ],
            options={
                'db_table': 'resultado_indicador',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='activo', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuestas.institucion')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuestas.rol')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
        migrations.DeleteModel(
            name='RespuestaEncuesta',
        ),
        migrations.DeleteModel(
            name='RespuestaItem',
        ),
    ]
